### PR TITLE
Better solution for race condition cleanup

### LINKED ISSUE #6: Race conditions in cleanup code
(I mentioned this on irc, but you also get a proper report.)

## Problem

`createRedirectedProcess` contains this bit:

https://github.com/reflex-frp/reflex-process/blob/29b83cfcf5e14656c43ad97de31727a81049287a/src/Reflex/Process.hs#L103-L107

I think there are problems with this:
- There is no guarantee that the output threads forked in lines 92 and 98 above have finished processing. This is most relevant if the started process prints interesting info right before quitting on its own accord.
    https://github.com/reflex-frp/reflex-process/blob/29b83cfcf5e14656c43ad97de31727a81049287a/src/Reflex/Process.hs#L89-L101
- As a consequence, `cleanupProcess` closing handles means that these threads may run into exceptions ("read on closed handle") but they _also_ get killed. So the network might not get events for stdout/stderr happening right before child process shutdown, plus a potential exception.
- Also, why mask the `ecTrigger ec`? Maybe this is harmless, but I don't see the benefit to masking in this fashion - `waitForProcess` is not masked anyway, so you get little guarantee. I assume that `waitForProcess` is interruptible so I _could_ see a purpose in masking the whole block. Not sure though, async exceptions are always tricky.

## Relevance

For "daemon" type child processes the existing code probably works fine, but if you start short-lived processes via this interface, it is definitely possible to not get any output captured as a consequence of this. I observed this already. And this error is silent, too.

## Proposed Solution

Afaict the only way to ensure that the forked threads have finished doing their job is waiting until they terminate. After that, you should be safe to kill them :) and to close the handles. But really, the threads should have a finally-block that does the closing. For the input handle (stdin of the child process) it is fine to close the handle when the child process has finished.

### PR DESCRIPTION
**Pull request by meditans**
Fixes #6 

This waits for the output handling threads to finish before firing the "process completed" event and cleaning up the process.

### CODE REVIEW

File: src/Reflex/Process.hs [hunk 1]
```diff
@@ -127,27 +146,38 @@ createProcess
...
+      return (liftIO . atomically . writeTChan channel)
+    output h processFinished trigger = do
       H.hSetBuffering h H.LineBuffering
       let go = do
             open <- H.hIsOpen h
             when open $ do
               readable <- H.hIsReadable h
               when readable $ do
-                out <- BS.hGetSome h 32768
+                out <- BS.hGetNonBlocking h 32768
```
Comment (tomsmalley) [inline src/Reflex/Process.hs]: We really shouldn't make this a busy wait. Is this problem not solved by checking for `isEOF` here and letting the threads die naturally rather than killing/cancelling them?

**Review by tomsmalley — DISMISSED** [review]

File: src/Reflex/Process.hs (hunk 1 above)
Comment (tomsmalley) [reply src/Reflex/Process.hs]: By "this problem" I mean the entire issue, not just this bit of code.

Comment (3noch) [reply src/Reflex/Process.hs]: Blocking `hGetSome` *should* get interrupted if the handle dies right?

Comment (tomsmalley) [reply src/Reflex/Process.hs]: I think so. From the docs for `hGet`:
> If the handle is a pipe or socket, and the writing end is closed, hGet will behave as if EOF was reached.

Comment (3noch) [reply src/Reflex/Process.hs]: @meditans was there something that caused you to switch to NonBlocking in the first place?

Comment (3noch) [reply src/Reflex/Process.hs]: You shouldn't even need to check for isEOF

Comment (meditans) [reply src/Reflex/Process.hs]: So, I thought about that and I welcome alternative solutions, or the reason for which that's not a problem; the issue I was trying to solve making that non-blocking is this:

* the underlying process dies
* it sets the `IORef` that signals that it died
* now the threads have the opportunity of finishing the work on the handle, but we still need a way of saying `we're done with the handles now`, so that we know it's safe to clean the process

 The reason for which I thought is not enough to just use `hGetSome` is that that function blocks on the empty handle. The case I was worried about is this, from the documentation of `hGetSome`:
 `hGetSome only blocks if there is no data available, and EOF has not yet been reached.`

I didn't want to be in a situation in which there's no data available, and no EOF is reached.
I see now that maybe my mental model of how a handle works was wrong; I though that when the underlying process died, there was no way of knowing it looking at the handle. If instead, when the underlying process dies, the handle hand all the data and then simulate an `EOF`, and then terminates, then I suggest to return back to the original code. But anyway, we need to know when this threads terminate so that we complete the cleanup.

@3noch @tomsmalley

Comment (meditans) [reply src/Reflex/Process.hs]: I think that the problem that this issue solves is that before, if the underlying process terminates, the handles are immediately closed, and there is a lot of data in the handles, we could have lose them; now we tell the threads that handle them that the code terminated, so they have a chance to use all the data in the handles. I don't see how just checking for `isEOF` there would alleviate this concern.

Comment (lspitzner) [reply src/Reflex/Process.hs]: > If instead, when the underlying process dies, the handle hand all the data and then simulate an `EOF`, and then terminates, then I suggest to return back to the original code.

I think that is exactly what happens.

~~~~
Prelude> import System.Process
Prelude System.Process> import Data.ByteString
Prelude System.Process Data.ByteString> import System.IO
Prelude System.Process Data.ByteString System.IO> (_,mOut,_,p) <- createProcess $ (shell "echo test") { std_out = CreatePipe }
Prelude System.Process Data.ByteString System.IO> getProcessExitCode p
Prelude System.Process Data.ByteString System.IO> mOut
Just {handle: fd:12}
Prelude System.Process Data.ByteString System.IO> Just h = mOut
Prelude System.Process Data.ByteString System.IO> h
{handle: fd:12}
Prelude System.Process Data.ByteString System.IO> hGetSome h 2
"te"
Prelude System.Process Data.ByteString System.IO> hGetSome h 2
"st"
Prelude System.Process Data.ByteString System.IO> hGetSome h 2
"\n"
Prelude System.Process Data.ByteString System.IO> hGetSome h 2
""
Prelude System.Process Data.ByteString System.IO> hGetSome h 2
""
Prelude System.Process Data.ByteString System.IO> hClose h
Prelude System.Process Data.ByteString System.IO> hGetSome h 2
*** Exception: fd:12: hGetBufSome: illegal operation (handle is closed)
Just ExitSuccess
~~~~

Comment (3noch) [reply src/Reflex/Process.hs]: @lspitzner Thank you that is exactly the test I wanted to run myself. The only additional check is that `hIsOpen` is still true in all those cases but I can't imagine it's set to false since this is the reading end of the pipe.

Comment (lspitzner) [reply src/Reflex/Process.hs]: yeah `hIsOpen h` keeps returning `True` until the `hClose h` invocation.

Comment (lspitzner) [reply src/Reflex/Process.hs]: that is, even if EOF is reached, the handle is still open (the reading end only I suppose, but that's what the handle corresponds to).

Comment (lspitzner) [reply src/Reflex/Process.hs]:
~~~~
Prelude System.Process Data.ByteString System.IO> hIsOpen h
True
Prelude System.Process Data.ByteString System.IO> hGetSome h 2
"\n"
Prelude System.Process Data.ByteString System.IO> hIsOpen h
True
Prelude System.Process Data.ByteString System.IO> hGetSome h 2
""
Prelude System.Process Data.ByteString System.IO> hIsOpen h
True
Prelude System.Process Data.ByteString System.IO> hClose h
Prelude System.Process Data.ByteString System.IO> hIsOpen h
False
~~~~

Comment (3noch) [reply src/Reflex/Process.hs]: I think I've fixed this.

File: src/Reflex/Process.hs [hunk 2]
```diff
@@ -96,30 +96,27 @@ createRedirectedProcess mkWriteStdInput mkReadStdOutput mkReadStdError p (Proces
...
-      void $ liftIO $ forkIO $ do
+      void $ liftIO $ async $ flip finally (P.cleanupProcess po) $ do
         waited <- waitForProcess ph
-        mask_ $ do
-          ecTrigger waited
-          P.cleanupProcess po
-          killThread outThread
-          killThread errThread
+        _ <- waitBoth outThread errThread
+        ecTrigger waited -- Output events should never fire after process completion
```
Comment (3noch) [inline src/Reflex/Process.hs:132]: This may be more convenient in many cases but it's also slightly less "honest".

Comment (3noch) [reply src/Reflex/Process.hs:132]: However without this we'd probably need a *second* event that fires when there is no output left to process.

Comment (3noch) [reply src/Reflex/Process.hs:132]: We should use 2 events instead?

Comment (3noch) [reply src/Reflex/Process.hs:132]: Need to document this invariant.

**Review by 3noch — APPROVED** [review]
